# Generated by Django 4.2.7 on 2024-07-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=300, unique=True)),
                ('actors', models.CharField(max_length=500)),
                ('directed_by', models.CharField(max_length=100)),
                ('produced_by', models.CharField(max_length=100)),
                ('music_directors', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=20)),
                ('release_date', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=300)),
                ('singers', models.CharField(max_length=300)),
                ('durations', models.CharField(max_length=300)),
                ('song_url', models.CharField(max_length=300)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.albums', to_field='album')),
            ],
        ),
    ]
